create table weather_observation (
    id bigint generated by default as identity primary key,
    station_name varchar(100) not null,
    wmo_code varchar(32) not null,
    air_temperature numeric(5,2) not null,
    wind_speed numeric(5,2) not null,
    weather_phenomenon varchar(255),
    observed_at timestamp with time zone not null
);

create index idx_weather_observation_station_observed_at
    on weather_observation (station_name, observed_at);

create index idx_weather_observation_wmo_code_observed_at
    on weather_observation (wmo_code, observed_at);
